// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUTNKDY2IGipMexsxAjZ28oyVUJbRm3GY',
    appId: '1:745002593519:web:b1ee7c4d476724b0b1bf1a',
    messagingSenderId: '745002593519',
    projectId: 'zero-8ff24',
    authDomain: 'zero-8ff24.firebaseapp.com',
    storageBucket: 'zero-8ff24.firebasestorage.app',
    measurementId: 'G-LRYTL1ENH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqifooa9yt_tf6ZJbAuzTBj6kg7z0nMNE',
    appId: '1:745002593519:android:a4cd56e99de2d1b0b1bf1a',
    messagingSenderId: '745002593519',
    projectId: 'zero-8ff24',
    storageBucket: 'zero-8ff24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo_VhOzWQSqcxPMcQLf61ZAj-dtsRaVr0',
    appId: '1:745002593519:ios:2f79fb54c2850111b1bf1a',
    messagingSenderId: '745002593519',
    projectId: 'zero-8ff24',
    storageBucket: 'zero-8ff24.firebasestorage.app',
    iosBundleId: 'com.example.zero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo_VhOzWQSqcxPMcQLf61ZAj-dtsRaVr0',
    appId: '1:745002593519:ios:2f79fb54c2850111b1bf1a',
    messagingSenderId: '745002593519',
    projectId: 'zero-8ff24',
    storageBucket: 'zero-8ff24.firebasestorage.app',
    iosBundleId: 'com.example.zero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUTNKDY2IGipMexsxAjZ28oyVUJbRm3GY',
    appId: '1:745002593519:web:ae2ec7fd4e26092ab1bf1a',
    messagingSenderId: '745002593519',
    projectId: 'zero-8ff24',
    authDomain: 'zero-8ff24.firebaseapp.com',
    storageBucket: 'zero-8ff24.firebasestorage.app',
    measurementId: 'G-KKY3DS1D7K',
  );
}
